### PR TITLE
Add count_instances probe

### PR DESCRIPTION
**Pull request by nazarenof**
Add tests for count_instances
Update README.md
Improve clarity in actions (mock naming).

### CODE REVIEW

**Comment by nazarenof** [comment]
Very well; added entry to the changelog.

**Comment by Lawouach** [comment]
In general, a PR should not change the version nor set the version in the changelog :)

**Comment by nazarenof** [comment]
Understood, will fix and push.

**Comment by nazarenof** [comment]
This is ready to be merged. Regards.

**Pull request merged**
